# 游戏参数设置
FPS = 30
FONT_SIZE=20 #字体大小

# 滑块设置
BOARD_SIZE = 4
TILE_SIZE = 80
SPEED_MOVE = int(TILE_SIZE / 8)

# 窗口设置
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 480
# 窗口边距
X_MARGIN_l = int((WINDOW_WIDTH / 2 - (TILE_SIZE * BOARD_SIZE + (BOARD_SIZE - 1))) / 2)
X_MARGIN_r = int(WINDOW_WIDTH/2) + X_MARGIN_l
Y_MARGIN = int((WINDOW_HEIGHT - (TILE_SIZE * BOARD_SIZE + (BOARD_SIZE - 1))) / 2)


# 色彩配置
BLACK = (0,0,0)
WHITE = (255,255,255)
BRIGHT_BLUE = (0,50,250)
GREEN = (0,205,0)
DARKTURQUOISE = (3,54,73)  # 深珠宝绿

BG_COLOR = DARKTURQUOISE
TILE_COLOR = GREEN
TEXT_COLOR = WHITE
BORDER_COLOR = BRIGHT_BLUE
BUTTON_COLOR = WHITE
BUTTON_TEXTCOLOR = BLACK
MESSAGE_COLOR = WHITE

# 动作配置
UP = 'up'
DOWN = 'down'
LEFT = 'left'
RIGHT = 'right'


